# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-14 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('author', models.CharField(max_length=20)),
                ('publisher', models.CharField(max_length=20)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('count', models.IntegerField()),
                ('issued_count', models.IntegerField(default=0)),
            ],
        ),
    ]
