# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-14 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='issued_book',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Book'),
        ),
    ]
